### ISSUE TITLE
JOSS Checklist

### ISSUE THREAD

**Issue by Jashcraf** [Jashcraf/katsu#15]
- [x] The software must be open source as per the [OSI definition](https://opensource.org/osd).
- [x] The software must be hosted at a location where users can open issues and propose code changes without manual approval of (or payment for) accounts.
- [x] The software must have an obvious research application.
- [x] You must be a major contributor to the software you are submitting, and have a GitHub account to participate in the review process.
- [x] Your paper must not focus on new research results accomplished with the software.
- [x] Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software.
 The paper may be in a short-lived branch which is never merged with the default, although if you do this, make sure this branch is created from the default so that it also includes the source code of your submission. 
- [x] Be stored in a repository that can be cloned without registration.
- [x] Be stored in a repository that is browsable online without registration.
- [x] Have an issue tracker that is readable without registration.
- [x] Permit individuals to create issues/file tickets against your repository.

## The JOSS paper

- [x] A list of the authors of the software and their affiliations.
- [x] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [x] A clear statement of need that illustrates the purpose of the software.
- [x] A description of how this software compares to other commonly-used packages in this research area.
- [x] Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it.
- [x] A list of key references including a link to the software archive.
